version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: tradeai_mongodb_live
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: trade_ai_production
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
    networks:
      - tradeai_network
    command: mongod --bind_ip_all --auth
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    container_name: tradeai_backend_live
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/trade_ai_production
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET:-tradeai-jwt-secret-2024-production-key-very-long-and-secure}
      - SESSION_SECRET=${SESSION_SECRET:-tradeai-session-secret-2024-production-key-very-long-and-secure}
      - CORS_ORIGIN=http://localhost:3000,http://127.0.0.1:3000
      - API_RATE_LIMIT=1000
      - LOG_LEVEL=info
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - tradeai_network
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
      args:
        - REACT_APP_API_URL=http://localhost:5000/api
        - REACT_APP_THEME=corporate
        - REACT_APP_VERSION=2.1.3
    container_name: tradeai_frontend_live
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - tradeai_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx Reverse Proxy (Optional - for production SSL)
  nginx:
    image: nginx:alpine
    container_name: tradeai_nginx_live
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - tradeai_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongodb_data:
    driver: local

networks:
  tradeai_network:
    driver: bridge