version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: trade-ai-mongodb
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init-production.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - trade-ai-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: trade-ai-redis
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - trade-ai-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    container_name: trade-ai-backend
    restart: always
    ports:
      - "5001:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      CORS_ORIGIN: "*"
    volumes:
      - ./logs:/app/logs
    networks:
      - trade-ai-network
    depends_on:
      - mongodb
      - redis

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
      args:
        REACT_APP_API_URL: http://13.247.139.75:5001/api
        REACT_APP_SOCKET_URL: ws://13.247.139.75:5001
    container_name: trade-ai-frontend
    restart: always
    ports:
      - "3001:80"
    networks:
      - trade-ai-network
    depends_on:
      - backend

  # AI Services
  ai-services:
    build:
      context: ./ai-services
      dockerfile: Dockerfile.production
    container_name: trade-ai-ai-services
    restart: always
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      MONGODB_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
    networks:
      - trade-ai-network
    depends_on:
      - mongodb
      - redis

  # Simple Nginx Proxy
  nginx:
    image: nginx:alpine
    container_name: trade-ai-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-simple.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - trade-ai-network
    depends_on:
      - frontend
      - backend

networks:
  trade-ai-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: