services:
  # MongoDB - ARM64 Compatible
  mongodb:
    image: mongo:6.0
    container_name: trade-ai-mongodb
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-TradeAI_Mongo_2024!}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-tradeai}
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - trade-ai-network
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s

  # Redis - ARM64 Compatible
  redis:
    image: redis:7-alpine
    container_name: trade-ai-redis
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-TradeAI_Redis_2024!}
    volumes:
      - redis_data:/data
    networks:
      - trade-ai-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Backend API - ARM64 Compatible
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    container_name: trade-ai-backend
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "5001:5000"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 5000
      MONGODB_URI: mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-TradeAI_Mongo_2024!}@mongodb:27017/${MONGO_DATABASE:-tradeai}?authSource=admin
      REDIS_URL: redis://:${REDIS_PASSWORD:-TradeAI_Redis_2024!}@redis:6379
      JWT_SECRET: ${JWT_SECRET:-TradeAI_JWT_Super_Secret_Key_2024_Change_This_In_Production}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-15m}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-TradeAI_JWT_Refresh_Secret_2024}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-7d}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    networks:
      - trade-ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend - ARM64 Compatible
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
      args:
        CACHEBUST: ${CACHEBUST:-1}
        REACT_APP_API_URL: ${REACT_APP_API_URL:-/api}
        REACT_APP_SOCKET_URL: ${REACT_APP_SOCKET_URL:-}
        REACT_APP_AI_API_URL: ${REACT_APP_AI_API_URL:-/ai}
        REACT_APP_MONITORING_URL: ${REACT_APP_MONITORING_URL:-/monitoring}
    container_name: trade-ai-frontend
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL:-/api}
      REACT_APP_SOCKET_URL: ${REACT_APP_SOCKET_URL:-}
      REACT_APP_AI_API_URL: ${REACT_APP_AI_API_URL:-/ai}
      REACT_APP_MONITORING_URL: ${REACT_APP_MONITORING_URL:-/monitoring}
    depends_on:
      - backend
    networks:
      - trade-ai-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health.json"]
      interval: 30s
      timeout: 10s
      retries: 3

  # AI Services - ARM64 Compatible
  ai-services:
    build:
      context: ./ai-services
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    container_name: trade-ai-ai-services
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8001:8000"
    environment:
      PORT: 8000
      HOST: 0.0.0.0
      MODEL_DIR: /app/models
      DATA_DIR: /app/data
      LOG_LEVEL: ${LOG_LEVEL:-info}
      MONGODB_URI: mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-TradeAI_Mongo_2024!}@mongodb:27017/${MONGO_DATABASE:-tradeai}?authSource=admin
      REDIS_URL: redis://:${REDIS_PASSWORD:-TradeAI_Redis_2024!}@redis:6379
    volumes:
      - ai_services_models:/app/models
      - ai_services_data:/app/data
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - trade-ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Monitoring Service - ARM64 Compatible
  monitoring:
    build:
      context: ./monitoring
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    container_name: trade-ai-monitoring
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8081:8080"
    environment:
      PORT: 8080
      HOST: 0.0.0.0
      LOG_LEVEL: ${LOG_LEVEL:-info}
      RETENTION_DAYS: ${RETENTION_DAYS:-30}
      SYSTEM_CHECK_INTERVAL: ${SYSTEM_CHECK_INTERVAL:-60}
      SERVICE_CHECK_INTERVAL: ${SERVICE_CHECK_INTERVAL:-300}
      BACKEND_URL: http://backend:5000
      FRONTEND_URL: http://frontend:80
      AI_SERVICES_URL: http://ai-services:8000
      MONGODB_URI: mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-TradeAI_Mongo_2024!}@mongodb:27017/${MONGO_DATABASE:-tradeai}?authSource=admin
      REDIS_URL: redis://:${REDIS_PASSWORD:-TradeAI_Redis_2024!}@redis:6379
    volumes:
      - monitoring_data:/app/data
    depends_on:
      - mongodb
      - redis
      - backend
      - ai-services
    networks:
      - trade-ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx (Production reverse proxy) - ARM64 Compatible
  nginx:
    image: nginx:alpine
    container_name: trade-ai-nginx
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-ssl.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - frontend
      - backend
      - ai-services
      - monitoring
    networks:
      - trade-ai-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health || exit 0"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  ai_services_models:
    driver: local
  ai_services_data:
    driver: local
  monitoring_data:
    driver: local

networks:
  trade-ai-network:
    driver: bridge