/**
 * MetricsRegistry
 *
 * Defines KPI metrics for each module with calculation logic,
 * thresholds, and visualization preferences.
 *
 * Structure: METRICS[module] = { metricId: { definition } }
 */

const METRICS = {
  budget: {
    totalBudget: {
      id: 'totalBudget',
      name: 'Total Budget',
      description: 'Total allocated budget amount',
      unit: 'currency',
      calculation: 'SUM(totalAmount)',
      aggregation: 'sum',
      format: 'currency',
      trend: 'neutral',
      category: 'financial'
    },
    budgetUtilization: {
      id: 'budgetUtilization',
      name: 'Budget Utilization',
      description: 'Percentage of budget spent vs allocated',
      unit: 'percentage',
      calculation: '(SUM(spentAmount) / SUM(totalAmount)) * 100',
      aggregation: 'average',
      format: 'percentage',
      trend: 'positive',
      thresholds: {
        critical: { min: 0, max: 50, color: 'red', label: 'Under-utilized' },
        warning: { min: 50, max: 75, color: 'yellow', label: 'Below target' },
        good: { min: 75, max: 95, color: 'green', label: 'On track' },
        danger: { min: 95, max: 100, color: 'orange', label: 'Near limit' },
        exceeded: { min: 100, max: Infinity, color: 'red', label: 'Over budget' }
      },
      category: 'financial'
    },
    budgetRemaining: {
      id: 'budgetRemaining',
      name: 'Budget Remaining',
      description: 'Remaining budget available for allocation',
      unit: 'currency',
      calculation: 'SUM(totalAmount) - SUM(spentAmount)',
      aggregation: 'sum',
      format: 'currency',
      trend: 'neutral',
      category: 'financial'
    },
    budgetBurnRate: {
      id: 'budgetBurnRate',
      name: 'Budget Burn Rate',
      description: 'Average daily budget consumption rate',
      unit: 'currency',
      calculation: 'SUM(spentAmount) / DAYS_ELAPSED',
      aggregation: 'average',
      format: 'currency',
      trend: 'neutral',
      category: 'financial'
    },
    projectedSpend: {
      id: 'projectedSpend',
      name: 'Projected Spend',
      description: 'Projected total spend based on current burn rate',
      unit: 'currency',
      calculation: '(SUM(spentAmount) / DAYS_ELAPSED) * TOTAL_DAYS',
      aggregation: 'sum',
      format: 'currency',
      trend: 'neutral',
      category: 'financial'
    }
  },

  promotion: {
    totalPromotions: {
      id: 'totalPromotions',
      name: 'Total Promotions',
      description: 'Total number of promotions',
      unit: 'count',
      calculation: 'COUNT(*)',
      aggregation: 'sum',
      format: 'number',
      trend: 'neutral',
      category: 'volume'
    },
    activePromotions: {
      id: 'activePromotions',
      name: 'Active Promotions',
      description: 'Number of currently active promotions',
      unit: 'count',
      calculation: 'COUNT(*) WHERE status = "active"',
      aggregation: 'sum',
      format: 'number',
      trend: 'neutral',
      category: 'volume'
    },
    promotionROI: {
      id: 'promotionROI',
      name: 'Promotion ROI',
      description: 'Return on investment for promotions',
      unit: 'percentage',
      calculation: '((incrementalRevenue - investedAmount) / investedAmount) * 100',
      aggregation: 'average',
      format: 'percentage',
      trend: 'positive',
      thresholds: {
        critical: { min: -Infinity, max: 0, color: 'red', label: 'Negative ROI' },
        warning: { min: 0, max: 50, color: 'yellow', label: 'Below target' },
        good: { min: 50, max: 150, color: 'green', label: 'On target' },
        excellent: { min: 150, max: Infinity, color: 'blue', label: 'Exceeding target' }
      },
      category: 'performance'
    },
    incrementalSales: {
      id: 'incrementalSales',
      name: 'Incremental Sales',
      description: 'Additional sales generated by promotions',
      unit: 'currency',
      calculation: 'SUM(actualSales) - SUM(baselineSales)',
      aggregation: 'sum',
      format: 'currency',
      trend: 'positive',
      category: 'financial'
    },
    promotionLift: {
      id: 'promotionLift',
      name: 'Promotion Lift',
      description: 'Percentage increase in sales vs baseline',
      unit: 'percentage',
      calculation: '((SUM(actualSales) - SUM(baselineSales)) / SUM(baselineSales)) * 100',
      aggregation: 'average',
      format: 'percentage',
      trend: 'positive',
      thresholds: {
        critical: { min: -Infinity, max: 0, color: 'red', label: 'Negative lift' },
        warning: { min: 0, max: 10, color: 'yellow', label: 'Below target' },
        good: { min: 10, max: 30, color: 'green', label: 'On target' },
        excellent: { min: 30, max: Infinity, color: 'blue', label: 'Exceeding target' }
      },
      category: 'performance'
    },
    promotionCost: {
      id: 'promotionCost',
      name: 'Promotion Cost',
      description: 'Total cost of promotions',
      unit: 'currency',
      calculation: 'SUM(investedAmount)',
      aggregation: 'sum',
      format: 'currency',
      trend: 'neutral',
      category: 'financial'
    }
  },

  tradeSpend: {
    totalTradeSpend: {
      id: 'totalTradeSpend',
      name: 'Total Trade Spend',
      description: 'Total trade spend committed',
      unit: 'currency',
      calculation: 'SUM(committedAmount)',
      aggregation: 'sum',
      format: 'currency',
      trend: 'neutral',
      category: 'financial'
    },
    tradeSpendAccruals: {
      id: 'tradeSpendAccruals',
      name: 'Trade Spend Accruals',
      description: 'Total accrued trade spend',
      unit: 'currency',
      calculation: 'SUM(accruedAmount)',
      aggregation: 'sum',
      format: 'currency',
      trend: 'neutral',
      category: 'financial'
    },
    tradeSpendAsPercentOfSales: {
      id: 'tradeSpendAsPercentOfSales',
      name: 'Trade Spend % of Sales',
      description: 'Trade spend as percentage of net sales',
      unit: 'percentage',
      calculation: '(SUM(accruedAmount) / SUM(netSales)) * 100',
      aggregation: 'average',
      format: 'percentage',
      trend: 'neutral',
      thresholds: {
        good: { min: 0, max: 15, color: 'green', label: 'Within target' },
        warning: { min: 15, max: 20, color: 'yellow', label: 'Above target' },
        critical: { min: 20, max: Infinity, color: 'red', label: 'Excessive' }
      },
      category: 'performance'
    },
    tradeSpendROI: {
      id: 'tradeSpendROI',
      name: 'Trade Spend ROI',
      description: 'Return on trade spend investment',
      unit: 'percentage',
      calculation: '((incrementalRevenue - accruedAmount) / accruedAmount) * 100',
      aggregation: 'average',
      format: 'percentage',
      trend: 'positive',
      category: 'performance'
    }
  },

  tradingTerm: {
    totalTradingTerms: {
      id: 'totalTradingTerms',
      name: 'Total Trading Terms',
      description: 'Total number of active trading terms',
      unit: 'count',
      calculation: 'COUNT(*) WHERE status = "active"',
      aggregation: 'sum',
      format: 'number',
      trend: 'neutral',
      category: 'volume'
    },
    tradingTermLiability: {
      id: 'tradingTermLiability',
      name: 'Trading Term Liability',
      description: 'Total outstanding liability from trading terms',
      unit: 'currency',
      calculation: 'SUM(accruedAmount) - SUM(settledAmount)',
      aggregation: 'sum',
      format: 'currency',
      trend: 'neutral',
      category: 'financial'
    },
    averageRebateRate: {
      id: 'averageRebateRate',
      name: 'Average Rebate Rate',
      description: 'Average rebate rate across all trading terms',
      unit: 'percentage',
      calculation: 'AVG(rate)',
      aggregation: 'average',
      format: 'percentage',
      trend: 'neutral',
      category: 'performance'
    },
    settlementCycle: {
      id: 'settlementCycle',
      name: 'Settlement Cycle',
      description: 'Average days to settle trading terms',
      unit: 'days',
      calculation: 'AVG(DATEDIFF(settlementDate, accrualDate))',
      aggregation: 'average',
      format: 'number',
      trend: 'negative',
      thresholds: {
        excellent: { min: 0, max: 30, color: 'green', label: 'Fast' },
        good: { min: 30, max: 60, color: 'blue', label: 'On target' },
        warning: { min: 60, max: 90, color: 'yellow', label: 'Slow' },
        critical: { min: 90, max: Infinity, color: 'red', label: 'Very slow' }
      },
      category: 'performance'
    }
  },

  activityGrid: {
    totalActivities: {
      id: 'totalActivities',
      name: 'Total Activities',
      description: 'Total number of marketing activities',
      unit: 'count',
      calculation: 'COUNT(*)',
      aggregation: 'sum',
      format: 'number',
      trend: 'neutral',
      category: 'volume'
    },
    activeActivities: {
      id: 'activeActivities',
      name: 'Active Activities',
      description: 'Number of currently active activities',
      unit: 'count',
      calculation: 'COUNT(*) WHERE status = "active"',
      aggregation: 'sum',
      format: 'number',
      trend: 'neutral',
      category: 'volume'
    },
    activityROI: {
      id: 'activityROI',
      name: 'Activity ROI',
      description: 'Return on investment for marketing activities',
      unit: 'percentage',
      calculation: '((incrementalRevenue - actualSpend) / actualSpend) * 100',
      aggregation: 'average',
      format: 'percentage',
      trend: 'positive',
      category: 'performance'
    },
    activitySpend: {
      id: 'activitySpend',
      name: 'Activity Spend',
      description: 'Total spend on marketing activities',
      unit: 'currency',
      calculation: 'SUM(actualSpend)',
      aggregation: 'sum',
      format: 'currency',
      trend: 'neutral',
      category: 'financial'
    },
    activityCompletionRate: {
      id: 'activityCompletionRate',
      name: 'Activity Completion Rate',
      description: 'Percentage of activities completed on time',
      unit: 'percentage',
      calculation: '(COUNT(*) WHERE completedOnTime = true / COUNT(*)) * 100',
      aggregation: 'average',
      format: 'percentage',
      trend: 'positive',
      thresholds: {
        critical: { min: 0, max: 50, color: 'red', label: 'Poor' },
        warning: { min: 50, max: 75, color: 'yellow', label: 'Below target' },
        good: { min: 75, max: 90, color: 'green', label: 'On target' },
        excellent: { min: 90, max: 100, color: 'blue', label: 'Excellent' }
      },
      category: 'performance'
    }
  },

  claim: {
    totalClaims: {
      id: 'totalClaims',
      name: 'Total Claims',
      description: 'Total number of claims',
      unit: 'count',
      calculation: 'COUNT(*)',
      aggregation: 'sum',
      format: 'number',
      trend: 'neutral',
      category: 'volume'
    },
    claimAmount: {
      id: 'claimAmount',
      name: 'Claim Amount',
      description: 'Total claim amount',
      unit: 'currency',
      calculation: 'SUM(claimAmount)',
      aggregation: 'sum',
      format: 'currency',
      trend: 'neutral',
      category: 'financial'
    },
    claimApprovalRate: {
      id: 'claimApprovalRate',
      name: 'Claim Approval Rate',
      description: 'Percentage of claims approved',
      unit: 'percentage',
      calculation: '(COUNT(*) WHERE status = "approved" / COUNT(*)) * 100',
      aggregation: 'average',
      format: 'percentage',
      trend: 'positive',
      thresholds: {
        critical: { min: 0, max: 50, color: 'red', label: 'Low' },
        warning: { min: 50, max: 75, color: 'yellow', label: 'Below target' },
        good: { min: 75, max: 90, color: 'green', label: 'On target' },
        excellent: { min: 90, max: 100, color: 'blue', label: 'Excellent' }
      },
      category: 'performance'
    },
    averageClaimProcessingTime: {
      id: 'averageClaimProcessingTime',
      name: 'Avg Claim Processing Time',
      description: 'Average days to process claims',
      unit: 'days',
      calculation: 'AVG(DATEDIFF(approvalDate, submissionDate))',
      aggregation: 'average',
      format: 'number',
      trend: 'negative',
      thresholds: {
        excellent: { min: 0, max: 5, color: 'green', label: 'Fast' },
        good: { min: 5, max: 10, color: 'blue', label: 'On target' },
        warning: { min: 10, max: 15, color: 'yellow', label: 'Slow' },
        critical: { min: 15, max: Infinity, color: 'red', label: 'Very slow' }
      },
      category: 'performance'
    },
    pendingClaims: {
      id: 'pendingClaims',
      name: 'Pending Claims',
      description: 'Number of claims pending approval',
      unit: 'count',
      calculation: 'COUNT(*) WHERE status = "pending"',
      aggregation: 'sum',
      format: 'number',
      trend: 'negative',
      category: 'volume'
    }
  },

  deduction: {
    totalDeductions: {
      id: 'totalDeductions',
      name: 'Total Deductions',
      description: 'Total number of deductions',
      unit: 'count',
      calculation: 'COUNT(*)',
      aggregation: 'sum',
      format: 'number',
      trend: 'negative',
      category: 'volume'
    },
    deductionAmount: {
      id: 'deductionAmount',
      name: 'Deduction Amount',
      description: 'Total deduction amount',
      unit: 'currency',
      calculation: 'SUM(amount)',
      aggregation: 'sum',
      format: 'currency',
      trend: 'negative',
      category: 'financial'
    },
    deductionResolutionRate: {
      id: 'deductionResolutionRate',
      name: 'Deduction Resolution Rate',
      description: 'Percentage of deductions resolved',
      unit: 'percentage',
      calculation: '(COUNT(*) WHERE status = "resolved" / COUNT(*)) * 100',
      aggregation: 'average',
      format: 'percentage',
      trend: 'positive',
      thresholds: {
        critical: { min: 0, max: 50, color: 'red', label: 'Low' },
        warning: { min: 50, max: 75, color: 'yellow', label: 'Below target' },
        good: { min: 75, max: 90, color: 'green', label: 'On target' },
        excellent: { min: 90, max: 100, color: 'blue', label: 'Excellent' }
      },
      category: 'performance'
    },
    averageResolutionTime: {
      id: 'averageResolutionTime',
      name: 'Avg Resolution Time',
      description: 'Average days to resolve deductions',
      unit: 'days',
      calculation: 'AVG(DATEDIFF(resolutionDate, identificationDate))',
      aggregation: 'average',
      format: 'number',
      trend: 'negative',
      thresholds: {
        excellent: { min: 0, max: 7, color: 'green', label: 'Fast' },
        good: { min: 7, max: 14, color: 'blue', label: 'On target' },
        warning: { min: 14, max: 30, color: 'yellow', label: 'Slow' },
        critical: { min: 30, max: Infinity, color: 'red', label: 'Very slow' }
      },
      category: 'performance'
    },
    validDeductionRate: {
      id: 'validDeductionRate',
      name: 'Valid Deduction Rate',
      description: 'Percentage of deductions deemed valid',
      unit: 'percentage',
      calculation: '(COUNT(*) WHERE resolution = "valid" / COUNT(*)) * 100',
      aggregation: 'average',
      format: 'percentage',
      trend: 'negative',
      category: 'performance'
    }
  },

  kamWallet: {
    totalWallets: {
      id: 'totalWallets',
      name: 'Total Wallets',
      description: 'Total number of KAM wallets',
      unit: 'count',
      calculation: 'COUNT(*)',
      aggregation: 'sum',
      format: 'number',
      trend: 'neutral',
      category: 'volume'
    },
    walletUtilization: {
      id: 'walletUtilization',
      name: 'Wallet Utilization',
      description: 'Percentage of wallet funds utilized',
      unit: 'percentage',
      calculation: '(SUM(spentAmount) / SUM(totalAllocation)) * 100',
      aggregation: 'average',
      format: 'percentage',
      trend: 'positive',
      thresholds: {
        critical: { min: 0, max: 50, color: 'red', label: 'Under-utilized' },
        warning: { min: 50, max: 75, color: 'yellow', label: 'Below target' },
        good: { min: 75, max: 95, color: 'green', label: 'On track' },
        danger: { min: 95, max: 100, color: 'orange', label: 'Near limit' }
      },
      category: 'performance'
    },
    walletBalance: {
      id: 'walletBalance',
      name: 'Wallet Balance',
      description: 'Total remaining wallet balance',
      unit: 'currency',
      calculation: 'SUM(totalAllocation) - SUM(spentAmount)',
      aggregation: 'sum',
      format: 'currency',
      trend: 'neutral',
      category: 'financial'
    },
    averageWalletSize: {
      id: 'averageWalletSize',
      name: 'Average Wallet Size',
      description: 'Average wallet allocation per KAM',
      unit: 'currency',
      calculation: 'AVG(totalAllocation)',
      aggregation: 'average',
      format: 'currency',
      trend: 'neutral',
      category: 'financial'
    }
  },

  campaign: {
    totalCampaigns: {
      id: 'totalCampaigns',
      name: 'Total Campaigns',
      description: 'Total number of campaigns',
      unit: 'count',
      calculation: 'COUNT(*)',
      aggregation: 'sum',
      format: 'number',
      trend: 'neutral',
      category: 'volume'
    },
    activeCampaigns: {
      id: 'activeCampaigns',
      name: 'Active Campaigns',
      description: 'Number of currently active campaigns',
      unit: 'count',
      calculation: 'COUNT(*) WHERE status = "active"',
      aggregation: 'sum',
      format: 'number',
      trend: 'neutral',
      category: 'volume'
    },
    campaignROI: {
      id: 'campaignROI',
      name: 'Campaign ROI',
      description: 'Return on investment for campaigns',
      unit: 'percentage',
      calculation: '((incrementalRevenue - actualSpend) / actualSpend) * 100',
      aggregation: 'average',
      format: 'percentage',
      trend: 'positive',
      thresholds: {
        critical: { min: -Infinity, max: 0, color: 'red', label: 'Negative ROI' },
        warning: { min: 0, max: 100, color: 'yellow', label: 'Below target' },
        good: { min: 100, max: 200, color: 'green', label: 'On target' },
        excellent: { min: 200, max: Infinity, color: 'blue', label: 'Exceeding target' }
      },
      category: 'performance'
    },
    campaignSpend: {
      id: 'campaignSpend',
      name: 'Campaign Spend',
      description: 'Total campaign spend',
      unit: 'currency',
      calculation: 'SUM(actualSpend)',
      aggregation: 'sum',
      format: 'currency',
      trend: 'neutral',
      category: 'financial'
    },
    campaignReach: {
      id: 'campaignReach',
      name: 'Campaign Reach',
      description: 'Total customers reached by campaigns',
      unit: 'count',
      calculation: 'SUM(customersReached)',
      aggregation: 'sum',
      format: 'number',
      trend: 'positive',
      category: 'volume'
    }
  },

  customer: {
    totalCustomers: {
      id: 'totalCustomers',
      name: 'Total Customers',
      description: 'Total number of customers',
      unit: 'count',
      calculation: 'COUNT(*)',
      aggregation: 'sum',
      format: 'number',
      trend: 'positive',
      category: 'volume'
    },
    activeCustomers: {
      id: 'activeCustomers',
      name: 'Active Customers',
      description: 'Number of active customers',
      unit: 'count',
      calculation: 'COUNT(*) WHERE status = "active"',
      aggregation: 'sum',
      format: 'number',
      trend: 'positive',
      category: 'volume'
    },
    customerRevenue: {
      id: 'customerRevenue',
      name: 'Customer Revenue',
      description: 'Total revenue from customers',
      unit: 'currency',
      calculation: 'SUM(revenue)',
      aggregation: 'sum',
      format: 'currency',
      trend: 'positive',
      category: 'financial'
    },
    averageRevenuePerCustomer: {
      id: 'averageRevenuePerCustomer',
      name: 'Avg Revenue per Customer',
      description: 'Average revenue per customer',
      unit: 'currency',
      calculation: 'SUM(revenue) / COUNT(*)',
      aggregation: 'average',
      format: 'currency',
      trend: 'positive',
      category: 'financial'
    }
  },

  product: {
    totalProducts: {
      id: 'totalProducts',
      name: 'Total Products',
      description: 'Total number of products',
      unit: 'count',
      calculation: 'COUNT(*)',
      aggregation: 'sum',
      format: 'number',
      trend: 'neutral',
      category: 'volume'
    },
    activeProducts: {
      id: 'activeProducts',
      name: 'Active Products',
      description: 'Number of active products',
      unit: 'count',
      calculation: 'COUNT(*) WHERE status = "active"',
      aggregation: 'sum',
      format: 'number',
      trend: 'neutral',
      category: 'volume'
    },
    productRevenue: {
      id: 'productRevenue',
      name: 'Product Revenue',
      description: 'Total revenue from products',
      unit: 'currency',
      calculation: 'SUM(revenue)',
      aggregation: 'sum',
      format: 'currency',
      trend: 'positive',
      category: 'financial'
    },
    averageRevenuePerProduct: {
      id: 'averageRevenuePerProduct',
      name: 'Avg Revenue per Product',
      description: 'Average revenue per product',
      unit: 'currency',
      calculation: 'SUM(revenue) / COUNT(*)',
      aggregation: 'average',
      format: 'currency',
      trend: 'positive',
      category: 'financial'
    }
  }
};

/**
 * Get metrics for a specific module
 */
const getMetrics = (module) => {
  return METRICS[module] || {};
};

/**
 * Get all metrics across all modules
 */
const getAllMetrics = () => {
  return METRICS;
};

/**
 * Get metric definition by module and metric ID
 */
const getMetric = (module, metricId) => {
  const moduleMetrics = METRICS[module];
  if (!moduleMetrics) {
    return null;
  }

  const metric = moduleMetrics[metricId];
  if (!metric) {
    return null;
  }

  return metric;
};

/**
 * Get metrics by category
 */
const getMetricsByCategory = (module, category) => {
  const moduleMetrics = METRICS[module];
  if (!moduleMetrics) return {};

  return Object.keys(moduleMetrics)
    .filter((key) => moduleMetrics[key].category === category)
    .reduce((acc, key) => {
      acc[key] = moduleMetrics[key];
      return acc;
    }, {});
};

/**
 * Format metric value based on format type
 */
const formatMetricValue = (value, format, currency = 'ZAR') => {
  if (value === null || value === undefined) return 'N/A';

  switch (format) {
    case 'currency':
      return new Intl.NumberFormat('en-ZA', {
        style: 'currency',
        currency
      }).format(value);

    case 'percentage':
      return `${value.toFixed(2)}%`;

    case 'number':
      return new Intl.NumberFormat('en-ZA').format(value);

    default:
      return value.toString();
  }
};

/**
 * Get threshold status for a metric value
 */
const getThresholdStatus = (metric, value) => {
  if (!metric.thresholds) return null;

  for (const [status, threshold] of Object.entries(metric.thresholds)) {
    if (value >= threshold.min && value < threshold.max) {
      return {
        status,
        ...threshold
      };
    }
  }

  return null;
};

/**
 * Get all modules with metrics
 */
const getAllModules = () => {
  return Object.keys(METRICS);
};

module.exports = {
  METRICS,
  getMetrics,
  getAllMetrics,
  getMetric,
  getMetricsByCategory,
  formatMetricValue,
  getThresholdStatus,
  getAllModules
};
