// GAP-07: PDF/Excel Export Service
// Uses lightweight CSV/HTML generation (no external packages)

export class ExportService {
  // Generate CSV from data array
  static toCSV(data, columns) {
    if (!data || !data.length) return '';
    const headers = columns || Object.keys(data[0]);
    const rows = data.map(row => headers.map(h => {
      const val = row[h.field || h] ?? '';
      const str = String(val).replace(/"/g, '""');
      return str.includes(',') || str.includes('"') || str.includes('\n') ? `"${str}"` : str;
    }));
    return [headers.map(h => h.label || h).join(','), ...rows.map(r => r.join(','))].join('\n');
  }

  // Generate HTML table for PDF-like export
  static toHTML(data, columns, title, companyName) {
    if (!data || !data.length) return '<html><body><p>No data</p></body></html>';
    const headers = columns || Object.keys(data[0]).map(k => ({ field: k, label: k }));
    return `<!DOCTYPE html>
<html><head><style>
body { font-family: Arial, sans-serif; margin: 20px; }
h1 { color: #1a237e; font-size: 24px; }
h2 { color: #666; font-size: 14px; margin-bottom: 20px; }
table { width: 100%; border-collapse: collapse; margin-top: 16px; }
th { background: #1a237e; color: white; padding: 10px 8px; text-align: left; font-size: 12px; }
td { padding: 8px; border-bottom: 1px solid #eee; font-size: 12px; }
tr:nth-child(even) { background: #f5f5f5; }
.footer { margin-top: 20px; font-size: 10px; color: #999; }
</style></head><body>
<h1>${title || 'Report'}</h1>
<h2>${companyName || 'TradeAI'} | Generated: ${new Date().toISOString().split('T')[0]}</h2>
<table>
<thead><tr>${headers.map(h => `<th>${h.label || h}</th>`).join('')}</tr></thead>
<tbody>${data.map(row => `<tr>${headers.map(h => `<td>${row[h.field || h] ?? ''}</td>`).join('')}</tr>`).join('')}</tbody>
</table>
<div class="footer">Generated by TradeAI Platform</div>
</body></html>`;
  }

  // Generate Excel XML (SpreadsheetML - opens in Excel without libraries)
  static toExcelXML(data, columns, sheetName) {
    if (!data || !data.length) return '';
    const headers = columns || Object.keys(data[0]).map(k => ({ field: k, label: k }));
    const rows = data.map(row =>
      `<Row>${headers.map(h => {
        const val = row[h.field || h] ?? '';
        const type = typeof val === 'number' ? 'Number' : 'String';
        return `<Cell><Data ss:Type="${type}">${String(val).replace(/&/g, '&amp;').replace(/</g, '&lt;')}</Data></Cell>`;
      }).join('')}</Row>`
    );
    return `<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
<Styles><Style ss:ID="header"><Font ss:Bold="1" ss:Color="#FFFFFF"/><Interior ss:Color="#1A237E" ss:Pattern="Solid"/></Style></Styles>
<Worksheet ss:Name="${sheetName || 'Sheet1'}">
<Table>
<Row ss:StyleID="header">${headers.map(h => `<Cell><Data ss:Type="String">${h.label || h}</Data></Cell>`).join('')}</Row>
${rows.join('\n')}
</Table></Worksheet></Workbook>`;
  }
}
